<?php

/**
 * Implements hook_image_effect_info().
 */
function rokka_effects_image_effect_info() {
  return array(
    'rokka_crop' => array(
      'label' => t('Rokka: Crop with background (*Rokka.io Only*)'),
      'help' => t('Cropping will remove portions of an image to make it the specified dimensions. Overcropping will increase the image size with a background.'),
      'effect callback' => 'image_crop_effect',
      'dimensions callback' => 'image_resize_dimensions',
      'form callback' => 'rokka_effects_crop_form',
      'summary theme' => 'rokka_effects_crop_summary',
    ),
  );
}

/**
 * Implements hook_theme().
 */
function rokka_effects_theme() {
  return array(
    'rokka_effects_crop_summary' => array(
      'variables' => array('data' => NULL),
    ),
  );
}

/**
 * Form structure for the image crop form.
 *
 * Note that this is not a complete form, it only contains the portion of the
 * form for configuring the crop options. Therefore it does not not need to
 * include metadata about the effect, nor a submit button.
 *
 * @param $data
 *   The current configuration for this crop effect.
 *
 * @return array
 */
function rokka_effects_crop_form($data) {
  $form = image_crop_form($data);

  $form['background_color'] = array(
    '#type' => 'textfield',
    '#default_value' => isset($data['background_color']) ? $data['background_color'] : '#000000',
    '#title' => t('Background color'),
    '#description' => t('The background color to use for exposed areas of the image. Use web-style hex colors (#FFFFFF for white, #000000 for black)'),
    '#size' => 7,
    '#maxlength' => 7,
    '#element_validate' => array('image_effect_color_validate'),
  );

  $form['background_opacity'] = array(
    '#type' => 'textfield',
    '#title' => t('Background opacity'),
    '#description' => t(''),
    '#default_value' => isset($data['background_opacity']) ? $data['background_opacity'] : 100,
    '#size' => 3,
    '#element_validate' => array('rokka_effects_opacity_validate'),
  );

  return $form;
}

/**
 * Returns HTML for a summary of an image resize effect.
 *
 * @param $variables
 *   An associative array containing:
 *   - data: The current configuration for this resize effect.
 *
 * @return string
 */
function theme_rokka_effects_crop_summary($variables) {
  $data = $variables['data'];

  if ($data['width'] && $data['height']) {
    return check_plain($data['width']) . 'x' . check_plain($data['height']). ' (background: ' . check_plain($data['background_color'].')');
  }
  else {
    return ($data['width']) ? t('width @width', array('@width' => $data['width'])) : t('height @height', array('@height' => $data['height']));
  }
}

/**
 * Element validate handler to ensure an opacity value value.
 */
function rokka_effects_opacity_validate($element, &$form_state) {
  $value = $element['#value'];
  if ($value != '' && (!is_numeric($value) || intval($value) < 0)) {
    form_error($element, t('!name must be a positive integer.', array('!name' => $element['#title'])));
  }
}
